// Code generated by protoc-gen-go from "message.proto"
// DO NOT EDIT!

package messages

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto & math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type XItem struct {
	Label            *string `protobuf:"bytes,1,req" json:"Label,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *XItem) Reset()         { *this = XItem{} }
func (this *XItem) String() string { return proto.CompactTextString(this) }

type XMessage struct {
	Project          *string  `protobuf:"bytes,1,req" json:"Project,omitempty"`
	Payload          []*XItem `protobuf:"bytes,2,rep" json:"Payload,omitempty"`
	Broadcast        *bool    `protobuf:"varint,3,req" json:"Broadcast,omitempty"`
	Signatures       []string `protobuf:"bytes,4,rep" json:"Signatures,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *XMessage) Reset()         { *this = XMessage{} }
func (this *XMessage) String() string { return proto.CompactTextString(this) }

func init() {
}
